# Generated by Django 3.2.15 on 2022-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('item_level', models.CharField(max_length=7)),
                ('battle_level', models.CharField(max_length=20)),
                ('expedition_level', models.CharField(max_length=20)),
                ('engraving', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=20)),
                ('card', models.CharField(max_length=20)),
                ('gem', models.CharField(max_length=20)),
                ('collection', models.CharField(max_length=20)),
                ('weapon_level', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('vitality', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
