# Generated by Django 3.2.15 on 2022-09-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='battle_level',
            new_name='character_battle_level',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='card',
            new_name='character_card',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='collection',
            new_name='character_class',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='engraving',
            new_name='character_engraving',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='expedition_level',
            new_name='character_equipment_level',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='gem',
            new_name='character_expedition_level',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='power',
            new_name='character_gem',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='item_level',
            new_name='character_item_level',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='character_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='stat',
            new_name='character_power',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='vitality',
            new_name='character_stat',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='weapon_level',
            new_name='character_vitality',
        ),
    ]
