# Generated by Django 3.2.15 on 2022-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20220906_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='character_battle_level',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_engraving',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_equipment_level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_expedition_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_gem',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_item_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_stat',
            field=models.CharField(max_length=200),
        ),
    ]
