# Generated by Django 3.2.15 on 2022-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_auto_20220907_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
