# Generated by Django 3.2.15 on 2022-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_alter_member_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='member',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
