# Generated by Django 3.2.15 on 2022-09-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0005_auto_20220919_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='character_battle_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_class',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_expedition_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_item_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='character_vitality',
            field=models.IntegerField(),
        ),
    ]
