# Generated by Django 3.2.15 on 2022-09-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_auto_20220920_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='character_name',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('before_data', models.CharField(max_length=200)),
                ('after_data', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('character_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild.member')),
            ],
        ),
    ]
